
{{
    config(
        materialized = 'table'
    )
}}

SELECT
    MD5('KANTAR' || 'PAYMENTS' || PAYMENTS.PAYMENT_METHOD || PAYMENTS.PAYMENT_STATUS || PAYMENTS.PAYMENT_AMOUNT) AS PAYMENT_SK,
    PAYMENTS.PAYMENT_ID AS SOURCE_PAYMENT_ID,
    DIM_ORDER.ORDER_SK,
    PAYMENTS.ORDER_ID AS SOURCE_ORDER_ID,
    PAYMENTS.PAYMENT_METHOD,
    PAYMENTS.PAYMENT_STATUS,
    PAYMENTS.PAYMENT_AMOUNT
FROM
    {{ ref('v_harmonized_kantar_payments') }} PAYMENTS
    LEFT OUTER JOIN {{ ref('t_domain_kantar_fact_orders') }} DIM_ORDER ON (DIM_ORDER.SOURCE_ORDER_ID = PAYMENTS.ORDER_ID)
