
SELECT
    CUSTOMERS.CUSTOMER_FIRST_NAME,
    CUSTOMERS.CUSTOMER_LAST_NAME,
    PAYMENTS.PAYMENT_METHOD,
    COALESCE(SUM(PAYMENTS.PAYMENT_AMOUNT), 0) AS TOTAL_AMOUNT
FROM
    {{ ref('t_domain_kantar_fact_payments') }} PAYMENTS
    INNER JOIN {{ ref('t_domain_kantar_fact_orders') }} ORDERS ON (ORDERS.ORDER_SK = PAYMENTS.ORDER_SK)
    LEFT OUTER JOIN {{ ref('t_domain_kantar_dim_customers') }} CUSTOMERS ON (ORDERS.CUSTOMER_SK = CUSTOMERS.CUSTOMER_SK)
GROUP BY
    1, 2, 3
