
version: 2

sources:
  - name: raw_nielsen
    description: Raw Nielsen Incoming Data
    tables:
      
      - name: customers
        description: Nielsen Customers File
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: true
        columns:
          - name: ID
            description: Primary Key
            tests:
              - unique
              - not_null
      
      - name: orders
        description: Nielsen Orders File
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: ID
            description: Primary key
            tests:
              - unique
              - not_null
          - name: USER_ID
            tests:
              - not_null
              - relationships:
                  to: source('raw_nielsen', 'customers')
                  field: ID
          - name: ORDER_DATE
            tests:
              - not_null
          - name: STATUS
            tests:
              - not_null
              - accepted_values:
                  values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
          - name: bq_insert_timestamp
            description: BigQuery Data Load Timestamp
            tests:
              - not_null
      
      - name: payments
        description: Nielsen Payments File
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: id
            description: Primary key
            tests:
              - unique
              - not_null
          - name: orderid
            tests:
              - not_null
              - relationships:
                  to: source('raw_nielsen', 'orders')
                  field: ID
          - name: paymentmethod
            tests:
              - not_null
          - name: status
            tests:
              - not_null
              - accepted_values:
                  values: ['success', 'fail']
          - name: amount
            tests:
              - not_null
          - name: bq_insert_timestamp
            description: BigQuery Data Load Timestamp
            tests:
              - not_null
        tests:
          - inner_relationship_check:
              source_model: source('raw_nielsen', 'orders')
              source_column_name: ID
              related_model: source('raw_nielsen', 'payments')
              related_column_name: orderid
