
version: 2

sources:
  - name: raw_nielsen
    description: Raw Nielsen Incoming Data
    tables:
      
      - name: v_raw_nielsen_customers
        description: Nielsen Customers Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: true
        columns:
          - name: ID
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null
      
      - name: v_raw_nielsen_orders
        description: Nielsen Orders Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: ID
            tests:
              - not_null
          - name: CUSTOMER_ID
            tests:
              - not_null
          - name: ORDER_DATE
            tests:
              - not_null
          - name: STATUS
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null
      
      - name: v_raw_nielsen_payments
        description: Nielsen Payments Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: id
            tests:
              - not_null
          - name: orderid
            tests:
              - not_null
          - name: paymentmethod
            tests:
              - not_null
          - name: status
            tests:
              - not_null
          - name: amount
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null

  - name: raw_kantar
    description: Raw Kantar Incoming Data
    tables:

      - name: v_raw_kantar_customers
        description: Kantar Customers Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: true
        columns:
          - name: ID
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null

      - name: v_raw_kantar_orders
        description: Kantar Orders Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: ID
            tests:
              - not_null
          - name: CUSTOMER_ID
            tests:
              - not_null
          - name: ORDER_DATE
            tests:
              - not_null
          - name: STATUS
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null

      - name: v_raw_kantar_payments
        description: Kantar Payments Raw Data
        config:
          meta:
            owner: Sudip
            email: bsudip48@yahoo.com
            contains_pii: false
        columns:
          - name: id
            tests:
              - not_null
          - name: orderid
            tests:
              - not_null
          - name: paymentmethod
            tests:
              - not_null
          - name: status
            tests:
              - not_null
          - name: amount
            tests:
              - not_null
          - name: BQ_INSERT_TIMESTAMP
            description: BigQuery Data Load Timestamp
            tests:
              - not_null
